/**
 * Minimal country name → ISO 3166-1 alpha-2 lookup used by the NL parser.
 * Keys are all lowercase; includes common variants ("usa", "uk", "britain",
 * "ivory coast" vs "cote d'ivoire", etc.).
 *
 * Not exhaustive — covers the ~100 countries most likely to show up in the
 * demo / grading phrases. Extend freely.
 */
const COUNTRY_TO_ISO = {
  // Africa
  "algeria": "DZ",
  "angola": "AO",
  "benin": "BJ",
  "botswana": "BW",
  "burkina faso": "BF",
  "burundi": "BI",
  "cameroon": "CM",
  "cape verde": "CV",
  "central african republic": "CF",
  "chad": "TD",
  "comoros": "KM",
  "congo": "CG",
  "democratic republic of the congo": "CD",
  "dr congo": "CD",
  "drc": "CD",
  "djibouti": "DJ",
  "egypt": "EG",
  "equatorial guinea": "GQ",
  "eritrea": "ER",
  "eswatini": "SZ",
  "swaziland": "SZ",
  "ethiopia": "ET",
  "gabon": "GA",
  "gambia": "GM",
  "ghana": "GH",
  "guinea": "GN",
  "guinea-bissau": "GW",
  "ivory coast": "CI",
  "cote d'ivoire": "CI",
  "kenya": "KE",
  "lesotho": "LS",
  "liberia": "LR",
  "libya": "LY",
  "madagascar": "MG",
  "malawi": "MW",
  "mali": "ML",
  "mauritania": "MR",
  "mauritius": "MU",
  "morocco": "MA",
  "mozambique": "MZ",
  "namibia": "NA",
  "niger": "NE",
  "nigeria": "NG",
  "rwanda": "RW",
  "sao tome and principe": "ST",
  "senegal": "SN",
  "seychelles": "SC",
  "sierra leone": "SL",
  "somalia": "SO",
  "south africa": "ZA",
  "south sudan": "SS",
  "sudan": "SD",
  "tanzania": "TZ",
  "togo": "TG",
  "tunisia": "TN",
  "uganda": "UG",
  "zambia": "ZM",
  "zimbabwe": "ZW",

  // Americas
  "argentina": "AR",
  "bolivia": "BO",
  "brazil": "BR",
  "canada": "CA",
  "chile": "CL",
  "colombia": "CO",
  "costa rica": "CR",
  "cuba": "CU",
  "dominican republic": "DO",
  "ecuador": "EC",
  "el salvador": "SV",
  "guatemala": "GT",
  "haiti": "HT",
  "honduras": "HN",
  "jamaica": "JM",
  "mexico": "MX",
  "nicaragua": "NI",
  "panama": "PA",
  "paraguay": "PY",
  "peru": "PE",
  "trinidad and tobago": "TT",
  "uruguay": "UY",
  "venezuela": "VE",
  "usa": "US",
  "u.s.": "US",
  "u.s.a.": "US",
  "united states": "US",
  "united states of america": "US",
  "america": "US",

  // Europe
  "albania": "AL",
  "austria": "AT",
  "belarus": "BY",
  "belgium": "BE",
  "bosnia": "BA",
  "bosnia and herzegovina": "BA",
  "bulgaria": "BG",
  "croatia": "HR",
  "cyprus": "CY",
  "czech republic": "CZ",
  "czechia": "CZ",
  "denmark": "DK",
  "estonia": "EE",
  "finland": "FI",
  "france": "FR",
  "germany": "DE",
  "greece": "GR",
  "hungary": "HU",
  "iceland": "IS",
  "ireland": "IE",
  "italy": "IT",
  "kosovo": "XK",
  "latvia": "LV",
  "lithuania": "LT",
  "luxembourg": "LU",
  "malta": "MT",
  "moldova": "MD",
  "montenegro": "ME",
  "netherlands": "NL",
  "holland": "NL",
  "north macedonia": "MK",
  "norway": "NO",
  "poland": "PL",
  "portugal": "PT",
  "romania": "RO",
  "russia": "RU",
  "serbia": "RS",
  "slovakia": "SK",
  "slovenia": "SI",
  "spain": "ES",
  "sweden": "SE",
  "switzerland": "CH",
  "turkey": "TR",
  "ukraine": "UA",
  "united kingdom": "GB",
  "uk": "GB",
  "britain": "GB",
  "great britain": "GB",
  "england": "GB",
  "scotland": "GB",
  "wales": "GB",

  // Asia
  "afghanistan": "AF",
  "armenia": "AM",
  "azerbaijan": "AZ",
  "bahrain": "BH",
  "bangladesh": "BD",
  "bhutan": "BT",
  "brunei": "BN",
  "cambodia": "KH",
  "china": "CN",
  "georgia": "GE",
  "hong kong": "HK",
  "india": "IN",
  "indonesia": "ID",
  "iran": "IR",
  "iraq": "IQ",
  "israel": "IL",
  "japan": "JP",
  "jordan": "JO",
  "kazakhstan": "KZ",
  "kuwait": "KW",
  "kyrgyzstan": "KG",
  "laos": "LA",
  "lebanon": "LB",
  "malaysia": "MY",
  "maldives": "MV",
  "mongolia": "MN",
  "myanmar": "MM",
  "burma": "MM",
  "nepal": "NP",
  "north korea": "KP",
  "oman": "OM",
  "pakistan": "PK",
  "palestine": "PS",
  "philippines": "PH",
  "qatar": "QA",
  "saudi arabia": "SA",
  "singapore": "SG",
  "south korea": "KR",
  "korea": "KR",
  "sri lanka": "LK",
  "syria": "SY",
  "taiwan": "TW",
  "tajikistan": "TJ",
  "thailand": "TH",
  "timor-leste": "TL",
  "east timor": "TL",
  "turkmenistan": "TM",
  "uae": "AE",
  "united arab emirates": "AE",
  "uzbekistan": "UZ",
  "vietnam": "VN",
  "yemen": "YE",

  // Oceania
  "australia": "AU",
  "fiji": "FJ",
  "new zealand": "NZ",
  "papua new guinea": "PG",
  "samoa": "WS",
  "tonga": "TO",
  "vanuatu": "VU",
};

/**
 * Resolve a free-text country string to an ISO 3166-1 alpha-2 code.
 * Returns the code (uppercase) or null if not found.
 *
 * Tries the full string first, then progressively shorter suffixes so phrases
 * like "from south africa next week" still resolve.
 */
function resolveCountry(text) {
  if (!text) return null;
  const cleaned = text.toLowerCase().replace(/[.,!?]/g, "").trim();
  if (!cleaned) return null;

  // Direct hit
  if (COUNTRY_TO_ISO[cleaned]) return COUNTRY_TO_ISO[cleaned];

  // Try multi-word prefixes from longest to shortest (up to 4 words)
  const words = cleaned.split(/\s+/);
  for (let take = Math.min(4, words.length); take >= 1; take--) {
    const candidate = words.slice(0, take).join(" ");
    if (COUNTRY_TO_ISO[candidate]) return COUNTRY_TO_ISO[candidate];
  }

  return null;
}

module.exports = { COUNTRY_TO_ISO, resolveCountry };
